// Applied production workshops. The same data is copied to site/ on the Node 18 branch.
const c = (zh, en) => ({ zh, en });
const lab = (title, explanation, metaphorTitle, metaphor, example, language, codeTitle, code, steps) => ({
  title, explanation, metaphorTitle, metaphor, example, language, codeTitle,
  code: code.join('\n'), steps,
});

export const productionConceptDetails = {
  t1: [lab(
    c('Production API 合約', 'A production API contract'),
    c('教學 demo 只要正常 request 成功；正式 API 仲要定義身份、輸入大小、schema、timeout、取消、錯誤碼同輸出契約。模型回覆係不可信資料，不能直接當成功 response。', 'A demo may only prove the happy path. A production API also defines identity, input limits, schema, timeouts, cancellation, error status, and the response contract. Model output remains untrusted data, not an automatically successful response.'),
    c('機場登機閘', 'An airport boarding gate'),
    c('登機唔係見到一張紙就放行；登機閘核對身份、航班、時間同可用座位。漏一項都要明確拒絕，唔可以假裝旅客已上機。', 'A boarding gate checks identity, flight, time, and capacity. A missing check must produce an explicit refusal, not a pretend successful boarding.'),
    c('退款助手收 orderId 同 question；backend 從 session 取 userId、限制輸入長度、用 5 秒總預算調模型，最後驗證 answer schema。', 'A refund assistant accepts orderId and question; the backend derives userId from the session, limits input size, gives the model a five-second budget, then validates the answer schema.'),
    'JavaScript', c('Bound the request at every edge', 'Bound the request at every edge'), [
      "async function answerRefund({ session, body, model }) {",
      "  if (!session?.userId) return { status: 401, error: 'unauthorized' };",
      "  if (typeof body.question !== 'string' || body.question.length > 1000)",
      "    return { status: 400, error: 'invalid_question' };",
      "  const signal = AbortSignal.timeout(5000);",
      "  const draft = await model({ userId: session.userId, question: body.question, signal });",
      "  if (typeof draft?.answer !== 'string') return { status: 502, error: 'invalid_model_output' };",
      "  return { status: 200, answer: draft.answer };",
      "}",
    ], [c('先寫 request/response contract 同身份來源。', 'Write the request/response contract and identity source.'), c('對 invalid、timeout、取消各寫一個測試。', 'Test invalid input, timeout, and cancellation separately.'), c('確認 secret、內部錯誤同原始 prompt 唔會回傳。', 'Confirm secrets, internal errors, and raw prompts never reach the client.')]),
  ],
  t2: [lab(
    c('Provider fallback 係政策決定', 'Provider fallback is a policy decision'),
    c('OpenRouter 可以在模型失敗後改用其他模型，但 fallback 唔一定只因網絡故障而發生：context 錯誤同 moderation refusal 亦可能觸發。新模型可能有唔同資料政策、成本、schema 能力同安全行為；正式環境要先批准同評測每個候選。', 'OpenRouter can try another model after a failure, but fallback is not limited to outages: context errors and moderation refusals may also trigger it. Another model may have different data practices, cost, schema support, and safety behavior. Approve and evaluate every candidate before production use.'),
    c('醫院轉診', 'A hospital referral'),
    c('主診醫生忙唔代表可以隨機交畀任何人；接手者要有相同資格、病歷權限同責任範圍。若原醫生因安全原因拒絕，唔應靠轉診繞過。', 'A busy clinician can be replaced only by someone qualified and authorized. A safety refusal should not be bypassed by routing to another person.'),
    c('分類 API 遇到 429 可轉往已評測候選；遇到 moderation refusal 就停止並交人，唔當作一般 retry。測試並記錄實際服務模型。', 'A classifier may switch to a pre-evaluated candidate on 429, but stops and escalates on a moderation refusal. Tests record the model that actually served the request.'),
    'JavaScript', c('Classify before trying an approved fallback', 'Classify before trying an approved fallback'), [
      "async function callWithPolicy(primary, backup, request) {",
      "  try { return await primary(request); }",
      "  catch (error) {",
      "    if (error.kind === 'moderation') return { status: 'human_review' };",
      "    if (!['rate_limit', 'unavailable'].includes(error.kind)) throw error;",
      "    if (!backup.approvedFor(request.dataClass)) throw error;",
      "    return backup.call(request); // validate output and record served model",
      "  }",
      "}",
    ], [c('列出可以 fallback 同必須停止嘅錯誤。', 'List errors that allow fallback and those that require stopping.'), c('每個候選檢查資料政策、能力同成本。', 'Check data policy, capabilities, and cost for each candidate.'), c('對原模型同 fallback 跑同一套品質/安全評測。', 'Run the same quality and safety suite on primary and fallback.')]),
  ],
  t3: [lab(
    c('RAG 文件更新、刪除同權限', 'RAG updates, deletion, and permissions'),
    c('RAG 唔係一次性建立 vector index。正式系統要同步來源版本、有效日期、撤回同刪除；查詢要先限制 tenant 同權限，再考慮相關度。否則舊政策或已刪文件可能繼續被引用。', 'RAG is not a one-time vector-index build. Production systems synchronize source versions, effective dates, withdrawal, and deletion; queries enforce tenant and access scope before relevance. Otherwise stale or deleted documents can still appear in answers.'),
    c('圖書館撤架記錄', 'A library withdrawal record'),
    c('一本書撤架後，目錄同推薦系統都要同步；唔可以只喺書架移走，搜尋結果仍叫人去借。會員卡亦決定邊啲收藏可見。', 'Withdrawing a book must update the catalog and recommendations, not only the physical shelf. Membership also controls which collections may be viewed.'),
    c('退款政策 v3 生效後，v2 不能再供一般查詢；一位客戶刪除資料後，向量索引與快取都要移除佢嘅文件。', 'When refund policy v3 becomes effective, v2 must leave ordinary retrieval. A customer deletion must also remove their documents from vector indexes and caches.'),
    'JavaScript', c('Filter before ranking', 'Filter before ranking'), [
      "function visiblePassages(index, context, now) {",
      "  return index.filter(row =>",
      "    row.tenantId === context.tenantId &&",
      "    context.allowedDocumentIds.has(row.documentId) &&",
      "    !row.deletedAt && row.effectiveAt <= now &&",
      "    (!row.expiresAt || row.expiresAt > now)",
      "  ); // then rank only this authorized set",
      "}",
    ], [c('為每個 chunk 保留 sourceId、版本、owner 同權限。', 'Store source ID, version, owner, and access scope on every chunk.'), c('寫 update/delete pipeline，包含索引同快取失效。', 'Build update/delete flows including index and cache invalidation.'), c('測試跨 tenant、撤回文件同過期政策均不可返回。', 'Test cross-tenant, withdrawn, and expired documents never return.')]),
  ],
  t4: [lab(
    c('Tool 安全攻防實驗', 'Tool-security attack lab'),
    c('Agent 可以讀取外部文件，但文件內容冇權改變工具權限。正式練習應故意放入 prompt injection，觀察模型會否提議越權 action，再由 host allowlist、authorization 同 approval 擋住副作用。', 'An agent can read external documents, but their text cannot grant tool authority. A production exercise plants an injection, observes whether the model proposes an unsafe action, and verifies the host blocks side effects using allowlists, authorization, and approval.'),
    c('公文夾入假命令', 'A forged instruction in a folder'),
    c('職員睇到文件寫「立即轉帳」唔代表文件有銀行簽名權；真正轉帳要用獨立身份同批核流程。', 'A paper saying “transfer funds now” does not have signing authority. The real transaction needs independent identity and approval.'),
    c('檢索到嘅退款政策內夾「export 全部客戶資料」；agent 可提議 export，但 host 無 export capability，測試必須證明零資料外洩。', 'A retrieved refund policy contains “export all customers.” The agent may propose it, but the host exposes no export capability; the test must prove zero data disclosure.'),
    'JavaScript', c('Enforce authority outside the model', 'Enforce authority outside the model'), [
      "function executeTool(proposal, context) {",
      "  const allowed = new Set(['read_own_order', 'draft_refund']);",
      "  if (!allowed.has(proposal.name)) throw new Error('tool_denied');",
      "  if (proposal.name === 'read_own_order' &&",
      "      !context.ownedOrderIds.has(proposal.orderId)) throw new Error('forbidden');",
      "  return tools[proposal.name](proposal, context);",
      "}",
    ], [c('畫出 untrusted text 去到 tool 嘅信任邊界。', 'Map the trust boundary from untrusted text to tools.'), c('準備 injection、越權同 PII 測試資料。', 'Create injection, privilege, and PII test cases.'), c('以 host log 證明 action 被拒，唔只睇模型回覆。', 'Prove denial from host logs, not merely model wording.')]),
    lab(
      c('Deep Agent：Context offload 與 delegation', 'Deep Agents: context offloading and delegation'),
      c('Deep Agent 唔係「更加聰明嘅模型」，而係一個 agent harness。Context 太大時有三個唔同選擇：把大型結果寫入 filesystem，只把路徑同摘要留喺 prompt；summarize 舊對話；或者用 subagent 隔離一個多步驟子任務。同步 subagent 會令 supervisor 等到完成，並只回傳一次 final handoff；需要長時間運行、並行、途中 steering 或 cancellation 時，應使用 async 工作模式。Delegation 亦有成本：多一次模型啟動、更多 latency、token 同失敗面，所以單一步驟工作唔應亂拆。', 'A Deep Agent is not a smarter model; it is an agent harness. When context grows, choose among three different mechanisms: write large results to a filesystem and retain only a path plus summary in the prompt; summarize older conversation; or isolate a multi-step subtask in a subagent. A synchronous subagent blocks its supervisor and returns one final handoff. Long-running or parallel work that needs mid-flight steering or cancellation calls for an asynchronous pattern. Delegation also adds a model startup, latency, tokens, and failure surface, so do not split simple one-step work.'),
      c('總廚、工作枱與專門廚房', 'Head chef, workbench, and specialist kitchen'),
      c('總廚把厚重食譜放喺工作枱，只記頁碼；繁忙時把舊 order 壓成摘要；糕點工作交去獨立餅房，收返一份完成報告。唔係每粒洋蔥都要開一間新廚房。', 'A head chef leaves a thick recipe on the workbench and remembers its page, summarizes old tickets, and sends pastry work to a specialist kitchen that returns one report. A new kitchen is not opened for every chopped onion.'),
      c('退款研究 supervisor 將政策 PDF 結果寫入 /workspace/evidence.json，delegates 一個只讀 policy-researcher 去比較版本，再收返包含引用、未知項同信心限制嘅短報告。付款工具永遠唔交俾 researcher。', 'A refund-research supervisor writes large policy results to /workspace/evidence.json, delegates version comparison to a read-only policy researcher, and receives a compact report with citations, unknowns, and confidence limits. The researcher never receives a payment tool.'),
      'JavaScript', c('Define a narrow handoff contract', 'Define a narrow handoff contract'), [
        "const policyResearcher = {",
        "  name: 'policy-researcher',",
        "  description: 'Compare approved policy versions and cite evidence',",
        "  systemPrompt: 'Read only. Return {findings, citations, unknowns}.',",
        "  tools: [searchApprovedPolicies], // no payment or customer-export tools",
        "};",
        "const agent = createDeepAgent({",
        "  model, subagents: [policyResearcher],",
        "  systemPrompt: 'Delegate only multi-step policy research; verify every handoff.',",
        "});",
      ], [c('先分類：存檔、摘要，定真正需要獨立推理嘅 delegation。', 'Classify the need: storage, summarization, or truly isolated reasoning.'), c('寫清 task、input、allowed tools、output schema、budget 同 stop condition。', 'Define task, inputs, allowed tools, output schema, budget, and stop condition.'), c('Supervisor 驗證 handoff、引用、成本同權限；subagent 結果唔係自動真確。', 'The supervisor verifies the handoff, citations, cost, and authorization; a subagent result is not automatically true.')]),
  ],
  t6: [lab(
    c('Trace、延遲同每次成功成本', 'Traces, latency, and cost per successful task'),
    c('正式監控要將 request、retrieval、model、tool 同回覆串成一條 trace。只記平均 latency 會遮住 p95 慢請求；只記 token 費用會忽略失敗重試。Logs 必須遮罩 PII 同 prompt 內容，並標示 model/prompt 版本。', 'Production telemetry connects the request, retrieval, model, tools, and response in one trace. Mean latency hides the slow p95 tail; token price alone hides failed retries. Logs redact PII and prompt content while recording model and prompt versions.'),
    c('包裹追蹤號碼', 'A parcel tracking number'),
    c('寄件、分揀、運送同簽收共用一個追蹤號；若只知道「平均三日到」，就搵唔到個別包裹卡喺邊。', 'Pickup, sorting, transport, and delivery share one tracking number. An average delivery time cannot locate a specific stuck parcel.'),
    c('退款助手每個 request 記 traceId、階段耗時、served model、token 同 outcome；dashboard 分開報 p95、錯誤率、越權阻擋率同每個成功答案成本。', 'Each refund request records trace ID, stage duration, served model, tokens, and outcome; the dashboard separates p95, error rate, denied actions, and cost per successful answer.'),
    'JavaScript', c('Record safe operational metadata', 'Record safe operational metadata'), [
      "function recordRun(run) {",
      "  return { traceId: run.traceId, promptVersion: run.promptVersion,",
      "    model: run.servedModel, durationMs: run.durationMs,",
      "    inputTokens: run.usage?.input_tokens ?? 0,",
      "    outputTokens: run.usage?.output_tokens ?? 0,",
      "    costUsd: run.costUsd, outcome: run.outcome };",
      "  // Do not log customer text, secret keys, or raw tool output.",
      "}",
    ], [c('定義 request/stage traceId 同版本欄位。', 'Define trace IDs and version fields for request and stages.'), c('計 p50/p95、錯誤率同每成功任務成本。', 'Compute p50/p95, error rate, and cost per successful task.'), c('模擬 429、timeout 同 malformed JSON，檢查告警。', 'Inject 429s, timeouts, and malformed JSON; verify alerts.')]),
    lab(
      c('LangSmith：由 trace 去到改進循環', 'LangSmith: from traces to an improvement loop'),
      c('LangSmith 係 observability 同 evaluation 平台，唔係令 agent 自動正確嘅 runtime。最細單位 run 類似一個 span；一次 request 入面嘅 model、retrieval 同 tool runs 組成 trace；多輪 session 用 thread_id 將多個 traces 串成 thread；trajectory 就係去除 nesting 後嘅訊息路徑。Metadata 記 app、model、prompt、dataset 同 release version，feedback 綁定特定 run。先用 production trace 找 failure，脫敏同人工審核後加入 dataset，再跑 offline regression；online evaluator 用抽樣流量監察 drift、異常同新 failure。', 'LangSmith is an observability and evaluation platform, not a runtime that makes agents correct. A run is like a span; model, retrieval, and tool runs for one request form a trace. A thread_id links traces across a multi-turn session, while a trajectory is the flattened message path. Metadata records app, model, prompt, dataset, and release versions, and feedback attaches to a specific run. Find failures in production traces, redact and review them before adding them to a dataset, run offline regressions, then use sampled online evaluation to detect drift, anomalies, and new failures.'),
      c('飛行記錄器加風洞', 'Flight recorder plus wind tunnel'),
      c('飛行記錄器講清楚一次航班每個系統發生咩事；工程師挑選脫敏事故去風洞重現，再將測試加入下一款飛機嘅出廠關卡。只收藏黑盒但從來唔做測試，唔會改善安全。', 'A flight recorder explains what happened across one flight. Engineers recreate a redacted incident in a wind tunnel and add it to the next release gate. Collecting black boxes without testing does not improve safety.'),
      c('退款 agent trace 顯示 retrieval 取到舊政策，tool 本身正常。團隊為 trace 加 promptVersion、modelVersion 同 policyIndexVersion，遮罩客戶文字，將失敗變成 dataset example；新版先過 deterministic citation check，再做 calibrated judge，同 baseline 比較後先 canary。', 'A refund-agent trace shows retrieval selected an obsolete policy while the tool behaved correctly. The team tags prompt, model, and policy-index versions, redacts customer text, and turns the failure into a dataset example. The new version must pass a deterministic citation check, then a calibrated judge, and beat the baseline before canary release.'),
      'JavaScript', c('Trace versions, not private content', 'Trace versions, not private content'), [
        "const answerRefund = traceable(async ({ safeQuestion, threadId }) => {",
        "  const evidence = await retrieveApprovedPolicy(safeQuestion);",
        "  return generateGroundedAnswer({ safeQuestion, evidence });",
        "}, {",
        "  name: 'answer-refund',",
        "  tags: ['refund', 'production'],",
        "  metadata: { appVersion: '2.4.0', promptVersion: 'refund-v7',",
        "    modelVersion: 'approved-primary', policyIndexVersion: '2026-09-21' },",
        "}); // keep secrets, raw PII, and unapproved documents out of traces",
      ], [c('設計 run/trace/thread 關係同非敏感版本 metadata。', 'Design run/trace/thread relationships and non-sensitive version metadata.'), c('用 deterministic checks 優先；judge 要 rubric、校準、抽樣同人工覆核。', 'Prefer deterministic checks; judges need rubrics, calibration, sampling, and human review.'), c('建立 trace → redact/review → dataset → offline regression → online monitor 閉環。', 'Build the trace → redact/review → dataset → offline regression → online monitor loop.')]),
  ],
  t13: [
    lab(
      c('Frozen eval + CI 發布關卡', 'Frozen evaluations and CI release gates'),
      c('Demo prompts 唔係代表性測試。建立有版本嘅正常、邊界、粵英雙語、資料缺失、越權同 prompt injection cases；每個 case 有預期行為、rubric 同 owner。報告分 slice 同 baseline，安全關鍵失敗要獨立阻止發布。', 'Demo prompts are not a representative test set. Version normal, edge, bilingual, missing-data, unauthorized, and injection cases with expected behavior, rubrics, and owners. Report by slice against a baseline; critical safety failures block release independently.'),
      c('橋樑負重測試', 'A bridge load test'),
      c('橋平均能承重唔夠；要測最危險跨度同極端天氣。修橋後同一組測試再跑，先知改動有冇令舊問題返嚟。', 'Average strength is insufficient; test the weakest span and extreme conditions. Re-run the same suite after every change to detect regressions.'),
      c('100 個合成退款案例分成 6 個 slices；新版 groundedness 較好，但跨 tenant case 一次失敗，CI 仍然 fail。', 'One hundred synthetic refund cases cover six slices. The new version improves groundedness but fails one cross-tenant case, so CI still fails.'),
      'JavaScript', c('Gate by critical slices', 'Gate by critical slices'), [
        "function releaseGate(report, baseline) {",
        "  const noUnauthorized = report.slices.authorization.failures === 0;",
        "  const noPiiLeaks = report.slices.pii.failures === 0;",
        "  const qualityOk = report.groundedness >= baseline.groundedness - 0.02;",
        "  return { pass: noUnauthorized && noPiiLeaks && qualityOk,",
        "    evidence: { dataset: report.datasetVersion, prompt: report.promptVersion } };",
        "}",
      ], [c('凍結合成 cases、預期行為同 rubric。', 'Freeze synthetic cases, expected behavior, and rubrics.'), c('同 baseline 比較整體、每個 slice 同 critical failure。', 'Compare overall, per-slice, and critical failures against baseline.'), c('在 CI 用同一條 gate 判斷 prompt/model/code 更新。', 'Gate prompt, model, and code changes in CI.')]),
    lab(
      c('Canary、回滾與事故 Runbook', 'Canary releases, rollback, and incident runbooks'),
      c('發佈唔係按下 deploy 就完成。先小流量 canary，監察 p95、錯誤、成本、品質同安全；預先寫明 stop、rollback、owner、證據保存同通知流程。事故後修復並加入 regression，再由頭過 gate。', 'A deploy is not the end of a release. Canary to a small audience while watching p95, errors, cost, quality, and safety. Predefine stop, rollback, owner, evidence preservation, and communication. After an incident, fix it, add a regression, and re-run the gate.'),
      c('消防演習', 'A fire drill'),
      c('火警時先搵電話號碼同出口會太遲；路線、負責人同集合點要事先寫清並演練。', 'Looking up exits and phone numbers during a fire is too late. Routes, owners, and meeting points must be written and practiced beforehand.'),
      c('5% 流量使用新 prompt；一旦出現越權讀取即停 canary、回滾上一版、保留脫敏 trace，同一個 case 變成永久測試。', 'Five percent of traffic uses the new prompt. An unauthorized read stops the canary, restores the prior version, preserves a redacted trace, and becomes a permanent regression case.'),
      'JavaScript', c('Automate the stop decision', 'Automate the stop decision'), [
        "function canaryDecision(metrics) {",
        "  if (metrics.unauthorizedActions > 0) return 'rollback';",
        "  if (metrics.p95Ms > metrics.limitP95Ms) return 'pause';",
        "  if (metrics.errorRate > metrics.limitErrorRate) return 'pause';",
        "  return 'continue';",
        "}",
      ], [c('發布前寫 owner、閾值、上一個穩定版本。', 'Record owner, thresholds, and prior stable version before rollout.'), c('用合成故障演練 stop、rollback 同通知。', 'Rehearse stop, rollback, and notification with synthetic failures.'), c('事故 case 脫敏後加入 frozen eval。', 'Redact incident evidence and add it to the frozen evaluation.')]),
  ],
};
